import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { CloneSession } from "@planarian/shared";
import { extractVisibleText } from "./htmlText.js";
import { getSessionRoot, readCloneSession } from "./sessionRepository.js";

export interface FormalScaffoldOptions {
  force?: boolean;
}

export interface FormalScaffoldResult {
  sessionId: string;
  formalCloneRoot: string;
  writtenFiles: string[];
  skippedFiles: string[];
}

interface ScaffoldFile {
  path: string;
  content: string;
}

interface ScaffoldRoute {
  url: string;
  routePath: string;
  appPath: string;
  title: string;
  sourceDir: string;
}

export async function createFormalCloneScaffold(
  projectRoot: string,
  sessionId: string,
  options: FormalScaffoldOptions = {}
): Promise<FormalScaffoldResult> {
  const session = await readCloneSession(projectRoot, sessionId);
  const sessionRoot = getSessionRoot(projectRoot, sessionId);
  const formalCloneRoot = path.join(sessionRoot, "formal-clone");
  const routes = await readCapturedScaffoldRoutes(sessionRoot);
  const files = renderFormalCloneScaffoldFiles(session, routes);
  const writtenFiles: string[] = [];
  const skippedFiles: string[] = [];

  for (const file of files) {
    const absolutePath = path.join(formalCloneRoot, file.path);
    await mkdir(path.dirname(absolutePath), { recursive: true });

    try {
      await writeFile(absolutePath, file.content, {
        encoding: "utf8",
        flag: options.force ? "w" : "wx"
      });
      writtenFiles.push(file.path);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "EEXIST" && !options.force) {
        skippedFiles.push(file.path);
        continue;
      }
      throw error;
    }
  }

  return {
    sessionId,
    formalCloneRoot,
    writtenFiles,
    skippedFiles
  };
}

export function renderFormalCloneScaffold(session: CloneSession): ScaffoldFile[] {
  return renderFormalCloneScaffoldFiles(session, []);
}

export function renderFormalCloneScaffoldFiles(session: CloneSession, routes: ScaffoldRoute[]): ScaffoldFile[] {
  const appName = `planarian-formal-clone-${session.sessionId}`;
  const title = session.target.title ?? session.target.hostname;

  const files: ScaffoldFile[] = [
    {
      path: "package.json",
      content: `${JSON.stringify(
        {
          name: appName,
          version: "0.1.0",
          private: true,
          type: "module",
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
            lint: "next lint"
          },
          dependencies: {
            "@next/env": "^15.0.0",
            next: "^15.0.0",
            react: "^19.0.0",
            "react-dom": "^19.0.0"
          },
          devDependencies: {
            "@types/node": "^22.10.2",
            "@types/react": "^19.0.0",
            "@types/react-dom": "^19.0.0",
            eslint: "^9.0.0",
            "eslint-config-next": "^15.0.0",
            typescript: "^5.7.2"
          }
        },
        null,
        2
      )}\n`
    },
    {
      path: "README.md",
      content: renderScaffoldReadme(session)
    },
    {
      path: "next.config.mjs",
      content: `/** @type {import("next").NextConfig} */\nconst nextConfig = {\n  outputFileTracingRoot: process.cwd()\n};\n\nexport default nextConfig;\n`
    },
    {
      path: "tsconfig.json",
      content: `${JSON.stringify(
        {
          compilerOptions: {
            target: "ES2017",
            lib: ["dom", "dom.iterable", "esnext"],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: "esnext",
            moduleResolution: "bundler",
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: "preserve",
            incremental: true,
            plugins: [{ name: "next" }]
          },
          include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
          exclude: ["node_modules"]
        },
        null,
        2
      )}\n`
    },
    {
      path: "next-env.d.ts",
      content: `/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// This file is generated by Planarian scaffold output.\n`
    },
    {
      path: "app/layout.tsx",
      content: `import type { Metadata } from "next";\nimport "./globals.css";\n\nexport const metadata: Metadata = {\n  title: ${JSON.stringify(title)},\n  description: ${JSON.stringify(`Formal clone scaffold for ${session.target.normalizedUrl}`)}\n};\n\nexport default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}\n`
    },
    {
      path: "app/page.tsx",
      content: `import target from "../data/target-summary.json";\n\nexport default function Home() {\n  return (\n    <main className="page-shell">\n      <section className="hero">\n        <p className="eyebrow">Planarian formal clone scaffold</p>\n        <h1>{target.title}</h1>\n        <p className="summary">\n          This is the first runnable scaffold for rebuilding the visible public UI of {target.url}.\n        </p>\n      </section>\n\n      <section className="panel" aria-labelledby="source-materials">\n        <h2 id="source-materials">Source materials</h2>\n        <ul>\n          <li>Review <code>../target-research/desktop.png</code> for visual matching.</li>\n          <li>Review <code>../target-research/raw-html.html</code> for content structure.</li>\n          <li>Use mock data for private or dynamic behavior.</li>\n        </ul>\n      </section>\n    </main>\n  );\n}\n`
    },
    {
      path: "app/globals.css",
      content: `:root {\n  color: #171717;\n  background: #f7f5ef;\n  font-family: Arial, Helvetica, sans-serif;\n}\n\n* {\n  box-sizing: border-box;\n}\n\nbody {\n  margin: 0;\n}\n\n.page-shell {\n  min-height: 100vh;\n  padding: 64px 24px;\n}\n\n.hero,\n.panel {\n  max-width: 920px;\n  margin: 0 auto 32px;\n}\n\n.eyebrow {\n  margin: 0 0 12px;\n  color: #5b6f55;\n  font-size: 13px;\n  font-weight: 700;\n  letter-spacing: 0;\n  text-transform: uppercase;\n}\n\nh1 {\n  max-width: 780px;\n  margin: 0;\n  font-size: 48px;\n  line-height: 1.08;\n}\n\n.summary {\n  max-width: 720px;\n  color: #4b4b4b;\n  font-size: 18px;\n  line-height: 1.6;\n}\n\n.panel {\n  border-top: 1px solid #d9d4c8;\n  padding-top: 24px;\n}\n\ncode {\n  font-size: 0.95em;\n}\n`
    },
    {
      path: "data/target-summary.json",
      content: `${JSON.stringify(
        {
          sessionId: session.sessionId,
          url: session.target.normalizedUrl,
          hostname: session.target.hostname,
          title,
          classification: session.target.classification,
          cloneMode: session.target.cloneMode,
          requiresAuth: session.target.requiresAuth,
          hasApiRequests: session.target.hasApiRequests,
          hasHeavyClientRendering: session.target.hasHeavyClientRendering,
          detectedFrameworks: session.target.detectedFrameworks,
          notes: session.target.notes
        },
        null,
        2
      )}\n`
    }
  ];

  const nonHomeRoutes = routes.filter((route) => route.routePath !== "/");
  if (nonHomeRoutes.length > 0) {
    files.push({
      path: "data/formal-routes.json",
      content: `${JSON.stringify(nonHomeRoutes, null, 2)}\n`
    });

    for (const route of nonHomeRoutes) {
      files.push({
        path: route.appPath,
        content: renderRoutePage(route, session)
      });
    }
  }

  return files;
}

function renderScaffoldReadme(session: CloneSession): string {
  return `# Formal Clone Scaffold

Target: ${session.target.normalizedUrl}

This directory is the formal clone work area generated by Planarian.

## Commands

\`\`\`bash
pnpm install
pnpm dev
pnpm build
\`\`\`

## Source Materials

- \`../TASK_BUNDLE.md\`
- \`../target-research/raw-html.html\`
- \`../target-research/desktop.png\`
- \`../target-research/network-analysis.json\`

## Safety

- Do not call private backend systems.
- Use mock data for authenticated, payment, trading, database, user-data, or private API behavior.
- Rebuild visible public UI only.
`;
}

async function readCapturedScaffoldRoutes(sessionRoot: string): Promise<ScaffoldRoute[]> {
  const manifestPath = path.join(sessionRoot, "target-research", "pages", "capture-manifest.json");
  let manifest: { pages?: Array<{ url: string; outputDir: string }> };

  try {
    manifest = JSON.parse(await readFile(manifestPath, "utf8")) as { pages?: Array<{ url: string; outputDir: string }> };
  } catch {
    return [];
  }

  const routes: ScaffoldRoute[] = [];
  for (const page of manifest.pages ?? []) {
    const route = await routeFromCapturedPage(sessionRoot, page);
    if (!route || routes.some((existing) => existing.routePath === route.routePath)) {
      continue;
    }
    routes.push(route);
  }

  return routes.sort((a, b) => a.routePath.localeCompare(b.routePath));
}

async function routeFromCapturedPage(
  sessionRoot: string,
  page: { url: string; outputDir: string }
): Promise<ScaffoldRoute | undefined> {
  let parsedUrl: URL;
  try {
    parsedUrl = new URL(page.url);
  } catch {
    return undefined;
  }

  const routePath = normalizeRoutePath(parsedUrl.pathname);
  const htmlPath = path.join(sessionRoot, page.outputDir, "raw-html.html");
  const title = (await readTitleFromHtml(htmlPath)) ?? titleFromRoutePath(routePath);
  const appPath = appPathForRoute(routePath);

  return {
    url: page.url,
    routePath,
    appPath,
    title,
    sourceDir: page.outputDir
  };
}

async function readTitleFromHtml(htmlPath: string): Promise<string | undefined> {
  try {
    const rawHtml = await readFile(htmlPath, "utf8");
    const h1 = firstMatchText(rawHtml, /<h1[^>]*>([\s\S]*?)<\/h1>/i);
    const title = firstMatchText(rawHtml, /<title[^>]*>([\s\S]*?)<\/title>/i);
    return h1 || title;
  } catch {
    return undefined;
  }
}

function normalizeRoutePath(pathname: string): string {
  const withoutTrailingSlash = pathname.replace(/\/+$/g, "");
  return withoutTrailingSlash === "" ? "/" : withoutTrailingSlash;
}

function appPathForRoute(routePath: string): string {
  if (routePath === "/") {
    return "app/page.tsx";
  }

  const segments = routePath
    .split("/")
    .filter(Boolean)
    .map((segment) => segment.replace(/[^a-zA-Z0-9._-]+/g, "-"));

  return path.posix.join("app", ...segments, "page.tsx");
}

function titleFromRoutePath(routePath: string): string {
  if (routePath === "/") {
    return "Home";
  }

  return routePath
    .split("/")
    .filter(Boolean)
    .map((segment) =>
      segment
        .split(/[-_]/g)
        .filter(Boolean)
        .map((word) => `${word.charAt(0).toUpperCase()}${word.slice(1)}`)
        .join(" ")
    )
    .join(" / ");
}

function firstMatchText(rawHtml: string, pattern: RegExp): string | undefined {
  const match = pattern.exec(rawHtml);
  return match ? extractVisibleText(match[1] ?? "") : undefined;
}

function renderRoutePage(route: ScaffoldRoute, session: CloneSession): string {
  return `const route = ${JSON.stringify(
    {
      title: route.title,
      url: route.url,
      routePath: route.routePath,
      sourceDir: route.sourceDir,
      target: session.target.normalizedUrl
    },
    null,
    2
  )};

export default function CapturedRoutePage() {
  return (
    <main className="page-shell">
      <section className="hero">
        <p className="eyebrow">Captured route scaffold</p>
        <h1>{route.title}</h1>
        <p className="summary">
          Rebuild this public route from the captured source materials for {route.routePath}.
        </p>
      </section>

      <section className="panel" aria-labelledby="route-materials">
        <h2 id="route-materials">Route source materials</h2>
        <ul>
          <li>Original URL: <a href={route.url}>{route.url}</a></li>
          <li>Captured HTML: <code>{route.sourceDir}/raw-html.html</code></li>
          <li>Captured screenshot: <code>{route.sourceDir}/desktop.png</code></li>
        </ul>
      </section>
    </main>
  );
}
`;
}
