import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { CloneSession } from "@planarian/shared";
import { getSessionRoot, readCloneSession } from "./sessionRepository.js";

export interface FormalScaffoldOptions {
  force?: boolean;
}

export interface FormalScaffoldResult {
  sessionId: string;
  formalCloneRoot: string;
  writtenFiles: string[];
  skippedFiles: string[];
}

interface ScaffoldFile {
  path: string;
  content: string;
}

export async function createFormalCloneScaffold(
  projectRoot: string,
  sessionId: string,
  options: FormalScaffoldOptions = {}
): Promise<FormalScaffoldResult> {
  const session = await readCloneSession(projectRoot, sessionId);
  const formalCloneRoot = path.join(getSessionRoot(projectRoot, sessionId), "formal-clone");
  const files = renderFormalCloneScaffold(session);
  const writtenFiles: string[] = [];
  const skippedFiles: string[] = [];

  for (const file of files) {
    const absolutePath = path.join(formalCloneRoot, file.path);
    await mkdir(path.dirname(absolutePath), { recursive: true });

    try {
      await writeFile(absolutePath, file.content, {
        encoding: "utf8",
        flag: options.force ? "w" : "wx"
      });
      writtenFiles.push(file.path);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "EEXIST" && !options.force) {
        skippedFiles.push(file.path);
        continue;
      }
      throw error;
    }
  }

  return {
    sessionId,
    formalCloneRoot,
    writtenFiles,
    skippedFiles
  };
}

export function renderFormalCloneScaffold(session: CloneSession): ScaffoldFile[] {
  const appName = `planarian-formal-clone-${session.sessionId}`;
  const title = session.target.title ?? session.target.hostname;

  return [
    {
      path: "package.json",
      content: `${JSON.stringify(
        {
          name: appName,
          version: "0.1.0",
          private: true,
          type: "module",
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
            lint: "next lint"
          },
          dependencies: {
            "@next/env": "^15.0.0",
            next: "^15.0.0",
            react: "^19.0.0",
            "react-dom": "^19.0.0"
          },
          devDependencies: {
            "@types/node": "^22.10.2",
            "@types/react": "^19.0.0",
            "@types/react-dom": "^19.0.0",
            eslint: "^9.0.0",
            "eslint-config-next": "^15.0.0",
            typescript: "^5.7.2"
          }
        },
        null,
        2
      )}\n`
    },
    {
      path: "README.md",
      content: renderScaffoldReadme(session)
    },
    {
      path: "next.config.mjs",
      content: `/** @type {import("next").NextConfig} */\nconst nextConfig = {};\n\nexport default nextConfig;\n`
    },
    {
      path: "tsconfig.json",
      content: `${JSON.stringify(
        {
          compilerOptions: {
            target: "ES2017",
            lib: ["dom", "dom.iterable", "esnext"],
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: "esnext",
            moduleResolution: "bundler",
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: "preserve",
            incremental: true,
            plugins: [{ name: "next" }]
          },
          include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
          exclude: ["node_modules"]
        },
        null,
        2
      )}\n`
    },
    {
      path: "next-env.d.ts",
      content: `/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// This file is generated by Planarian scaffold output.\n`
    },
    {
      path: "app/layout.tsx",
      content: `import type { Metadata } from "next";\nimport "./globals.css";\n\nexport const metadata: Metadata = {\n  title: ${JSON.stringify(title)},\n  description: ${JSON.stringify(`Formal clone scaffold for ${session.target.normalizedUrl}`)}\n};\n\nexport default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}\n`
    },
    {
      path: "app/page.tsx",
      content: `import target from "../data/target-summary.json";\n\nexport default function Home() {\n  return (\n    <main className="page-shell">\n      <section className="hero">\n        <p className="eyebrow">Planarian formal clone scaffold</p>\n        <h1>{target.title}</h1>\n        <p className="summary">\n          This is the first runnable scaffold for rebuilding the visible public UI of {target.url}.\n        </p>\n      </section>\n\n      <section className="panel" aria-labelledby="source-materials">\n        <h2 id="source-materials">Source materials</h2>\n        <ul>\n          <li>Review <code>../target-research/desktop.png</code> for visual matching.</li>\n          <li>Review <code>../target-research/raw-html.html</code> for content structure.</li>\n          <li>Use mock data for private or dynamic behavior.</li>\n        </ul>\n      </section>\n    </main>\n  );\n}\n`
    },
    {
      path: "app/globals.css",
      content: `:root {\n  color: #171717;\n  background: #f7f5ef;\n  font-family: Arial, Helvetica, sans-serif;\n}\n\n* {\n  box-sizing: border-box;\n}\n\nbody {\n  margin: 0;\n}\n\n.page-shell {\n  min-height: 100vh;\n  padding: 64px 24px;\n}\n\n.hero,\n.panel {\n  max-width: 920px;\n  margin: 0 auto 32px;\n}\n\n.eyebrow {\n  margin: 0 0 12px;\n  color: #5b6f55;\n  font-size: 13px;\n  font-weight: 700;\n  letter-spacing: 0;\n  text-transform: uppercase;\n}\n\nh1 {\n  max-width: 780px;\n  margin: 0;\n  font-size: 48px;\n  line-height: 1.08;\n}\n\n.summary {\n  max-width: 720px;\n  color: #4b4b4b;\n  font-size: 18px;\n  line-height: 1.6;\n}\n\n.panel {\n  border-top: 1px solid #d9d4c8;\n  padding-top: 24px;\n}\n\ncode {\n  font-size: 0.95em;\n}\n`
    },
    {
      path: "data/target-summary.json",
      content: `${JSON.stringify(
        {
          sessionId: session.sessionId,
          url: session.target.normalizedUrl,
          hostname: session.target.hostname,
          title,
          classification: session.target.classification,
          cloneMode: session.target.cloneMode,
          requiresAuth: session.target.requiresAuth,
          hasApiRequests: session.target.hasApiRequests,
          hasHeavyClientRendering: session.target.hasHeavyClientRendering,
          detectedFrameworks: session.target.detectedFrameworks,
          notes: session.target.notes
        },
        null,
        2
      )}\n`
    }
  ];
}

function renderScaffoldReadme(session: CloneSession): string {
  return `# Formal Clone Scaffold

Target: ${session.target.normalizedUrl}

This directory is the formal clone work area generated by Planarian.

## Commands

\`\`\`bash
pnpm install
pnpm dev
pnpm build
\`\`\`

## Source Materials

- \`../TASK_BUNDLE.md\`
- \`../target-research/raw-html.html\`
- \`../target-research/desktop.png\`
- \`../target-research/network-analysis.json\`

## Safety

- Do not call private backend systems.
- Use mock data for authenticated, payment, trading, database, user-data, or private API behavior.
- Rebuild visible public UI only.
`;
}

